# Required to run your project under the correct environment.

language: php

# Versions of PHP you want your project run with.

php:

 - 7.2

# Commands to be run before your environment runs.


# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
 - mysql


# After a build, send email notification with the build results
notifications:
 email: pradapadwani.a@spi-global.com
